name: Auto Update IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-browser-parser:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Скачиваем файлы
      uses: actions/checkout@v4

    - name: Включаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Устанавливаем библиотеки
      run: |
        pip install playwright
        playwright install chromium --with-deps

    - name: Запускаем кликер
      run: python parser.py

    - name: Проверяем результат и сохраняем
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -f playlist.m3u ]; then
          git add playlist.m3u
          git commit -m "Обновление плейлиста"
          git push
        else
          echo "Файл плейлиста не найден!"
        fi

    - name: Загружаем скриншот ошибки (если он есть)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screen-drop
        path: error_screen.png
        - name: Commit and Push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add playlist.m3u
        git commit -m "Auto-update playlist" || echo "No changes to commit"
        git push

